language: node_js
node_js:
  - '7'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  -export TZ=US/Pacific
after_script:
  - codeclimate-test-reporter < coverage/lcov.info
